version: '2.2'
services:
  reverse-proxy:
    build: .
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    network_mode: bridge
    scale: 3
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"

# docker-compose -f docker-compose.dev.yml up --build
