version: '2'
services:
  reverse-proxy:
    image: traefik:1.7
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
