# General
debug = true
logLevel = "DEBUG"

# Entrypoints
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/opt/traefik/certs/default.crt"
      keyFile = "/opt/traefik/certs/default.key"

# Web Dashboard
[web]
address = ":8080"

# Docker config
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
